package com.example.designsystem.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val Green40 = Color(0xFF2E7D32)
val GreenGrey40 = Color(0xFF546E7A)
val Lime40 = Color(0xFF9CCC65)

val OceanBlue = Color(0xFF1565C0)
val OceanTeal = Color(0xFF00838F)
val OceanAccent = Color(0xFF26C6DA)

val SunsetOrange = Color(0xFFF4511E)
val SunsetPink = Color(0xFFD81B60)
val SunsetYellow = Color(0xFFFFB300)


// RedVine Color Palette by HEX: #B33B15
// Light Theme Colors
internal val primaryLightRedVine = Color(0xFF902500)
internal val onPrimaryLightRedVine = Color(0xFFFFFFFF)
internal val primaryContainerLightRedVine = Color(0xFFB33B15)
internal val onPrimaryContainerLightRedVine = Color(0xFFFFDAD0)
internal val secondaryLightRedVine = Color(0xFF8E4C39)
internal val onSecondaryLightRedVine = Color(0xFFFFFFFF)
internal val secondaryContainerLightRedVine = Color(0xFFFEA991)
internal val onSecondaryContainerLightRedVine = Color(0xFF793B29)
internal val tertiaryLightRedVine = Color(0xFF745B00)
internal val onTertiaryLightRedVine = Color(0xFFFFFFFF)
internal val tertiaryContainerLightRedVine = Color(0xFFC8A84A)
internal val onTertiaryContainerLightRedVine = Color(0xFF4F3D00)
internal val errorLightRedVine = Color(0xFFBA1A1A)
internal val onErrorLightRedVine = Color(0xFFFFFFFF)
internal val errorContainerLightRedVine = Color(0xFFFFDAD6)
internal val onErrorContainerLightRedVine = Color(0xFF93000A)
internal val backgroundLightRedVine = Color(0xFFFFF8F6)
internal val onBackgroundLightRedVine = Color(0xFF251915)
internal val surfaceLightRedVine = Color(0xFFFFF8F6)
internal val onSurfaceLightRedVine = Color(0xFF251915)
internal val surfaceVariantLightRedVine = Color(0xFFFEDBD2)
internal val onSurfaceVariantLightRedVine = Color(0xFF59413B)
internal val outlineLightRedVine = Color(0xFF8C7169)
internal val outlineVariantLightRedVine = Color(0xFFE0BFB7)
internal val scrimLightRedVine = Color(0xFF000000)
internal val inverseSurfaceLightRedVine = Color(0xFF3C2D29)
internal val inverseOnSurfaceLightRedVine = Color(0xFFFFEDE8)
internal val inversePrimaryLightRedVine = Color(0xFFFFB5A0)
internal val surfaceDimLightRedVine = Color(0xFFEDD5CF)
internal val surfaceBrightLightRedVine = Color(0xFFFFF8F6)
internal val surfaceContainerLowestLightRedVine = Color(0xFFFFFFFF)
internal val surfaceContainerLowLightRedVine = Color(0xFFFFF1ED)
internal val surfaceContainerLightRedVine = Color(0xFFFFE9E4)
internal val surfaceContainerHighLightRedVine = Color(0xFFFBE3DD)
internal val surfaceContainerHighestLightRedVine = Color(0xFFF6DDD7)

// Dark Theme Colors
internal val primaryDarkRedVine = Color(0xFFFFB5A0)
internal val onPrimaryDarkRedVine = Color(0xFF5F1500)
internal val primaryContainerDarkRedVine = Color(0xFFB33B15)
internal val onPrimaryContainerDarkRedVine = Color(0xFFFFDAD0)
internal val secondaryDarkRedVine = Color(0xFFFFB5A0)
internal val onSecondaryDarkRedVine = Color(0xFF552010)
internal val secondaryContainerDarkRedVine = Color(0xFF713524)
internal val onSecondaryContainerDarkRedVine = Color(0xFFF4A088)
internal val tertiaryDarkRedVine = Color(0xFFE5C362)
internal val onTertiaryDarkRedVine = Color(0xFF3D2F00)
internal val tertiaryContainerDarkRedVine = Color(0xFFC8A84A)
internal val onTertiaryContainerDarkRedVine = Color(0xFF4F3D00)
internal val errorDarkRedVine = Color(0xFFFFB4AB)
internal val onErrorDarkRedVine = Color(0xFF690005)
internal val errorContainerDarkRedVine = Color(0xFF93000A)
internal val onErrorContainerDarkRedVine = Color(0xFFFFDAD6)
internal val backgroundDarkRedVine = Color(0xFF1C110D)
internal val onBackgroundDarkRedVine = Color(0xFFF6DDD7)
internal val surfaceDarkRedVine = Color(0xFF1C110D)
internal val onSurfaceDarkRedVine = Color(0xFFF6DDD7)
internal val surfaceVariantDarkRedVine = Color(0xFF59413B)
internal val onSurfaceVariantDarkRedVine = Color(0xFFE0BFB7)
internal val outlineDarkRedVine = Color(0xFFA88A82)
internal val outlineVariantDarkRedVine = Color(0xFF59413B)
internal val scrimDarkRedVine = Color(0xFF000000)
internal val inverseSurfaceDarkRedVine = Color(0xFFF6DDD7)
internal val inverseOnSurfaceDarkRedVine = Color(0xFF3C2D29)
internal val inversePrimaryDarkRedVine = Color(0xFFAB350F)
internal val surfaceDimDarkRedVine = Color(0xFF1C110D)
internal val surfaceBrightDarkRedVine = Color(0xFF453632)
internal val surfaceContainerLowestDarkRedVine = Color(0xFF160B08)
internal val surfaceContainerLowDarkRedVine = Color(0xFF251915)
internal val surfaceContainerDarkRedVine = Color(0xFF291D19)
internal val surfaceContainerHighDarkRedVine = Color(0xFF352723)
internal val surfaceContainerHighestDarkRedVine = Color(0xFF40312D)

// Forest Color Palette by HEX: #63A002
// Light Theme Colors
internal val primaryLightForest = Color(0xFF3E6700)
internal val onPrimaryLightForest = Color(0xFFFFFFFF)
internal val primaryContainerLightForest = Color(0xFF4F8200)
internal val onPrimaryContainerLightForest = Color(0xFFF9FFEA)
internal val secondaryLightForest = Color(0xFF4B662A)
internal val onSecondaryLightForest = Color(0xFFFFFFFF)
internal val secondaryContainerLightForest = Color(0xFFCCEEA1)
internal val onSecondaryContainerLightForest = Color(0xFF516D2F)
internal val tertiaryLightForest = Color(0xFF00694E)
internal val onTertiaryLightForest = Color(0xFFFFFFFF)
internal val tertiaryContainerLightForest = Color(0xFF008564)
internal val onTertiaryContainerLightForest = Color(0xFFF5FFF8)
internal val errorLightForest = Color(0xFFBA1A1A)
internal val onErrorLightForest = Color(0xFFFFFFFF)
internal val errorContainerLightForest = Color(0xFFFFDAD6)
internal val onErrorContainerLightForest = Color(0xFF93000A)
internal val backgroundLightForest = Color(0xFFF7FBEA)
internal val onBackgroundLightForest = Color(0xFF191D13)
internal val surfaceLightForest = Color(0xFFF7FBEA)
internal val onSurfaceLightForest = Color(0xFF191D13)
internal val surfaceVariantLightForest = Color(0xFFDEE6CD)
internal val onSurfaceVariantLightForest = Color(0xFF424937)
internal val outlineLightForest = Color(0xFF727A66)
internal val outlineVariantLightForest = Color(0xFFC2CAB2)
internal val scrimLightForest = Color(0xFF000000)
internal val inverseSurfaceLightForest = Color(0xFF2E3227)
internal val inverseOnSurfaceLightForest = Color(0xFFEFF3E2)
internal val inversePrimaryLightForest = Color(0xFF97D945)
internal val surfaceDimLightForest = Color(0xFFD8DCCC)
internal val surfaceBrightLightForest = Color(0xFFF7FBEA)
internal val surfaceContainerLowestLightForest = Color(0xFFFFFFFF)
internal val surfaceContainerLowLightForest = Color(0xFFF2F5E5)
internal val surfaceContainerLightForest = Color(0xFFECF0DF)
internal val surfaceContainerHighLightForest = Color(0xFFE6EADA)
internal val surfaceContainerHighestLightForest = Color(0xFFE0E4D4)

// Dark Theme Colors
internal val primaryDarkForest = Color(0xFF97D945)
internal val onPrimaryDarkForest = Color(0xFF1F3700)
internal val primaryContainerDarkForest = Color(0xFF64A104)
internal val onPrimaryContainerDarkForest = Color(0xFF192F00)
internal val secondaryDarkForest = Color(0xFFB1D188)
internal val onSecondaryDarkForest = Color(0xFF1F3700)
internal val secondaryContainerDarkForest = Color(0xFF365016)
internal val onSecondaryContainerDarkForest = Color(0xFFA3C37B)
internal val tertiaryDarkForest = Color(0xFF5DDCB0)
internal val onTertiaryDarkForest = Color(0xFF003828)
internal val tertiaryContainerDarkForest = Color(0xFF05A47C)
internal val onTertiaryContainerDarkForest = Color(0xFF002F21)
internal val errorDarkForest = Color(0xFFFFB4AB)
internal val onErrorDarkForest = Color(0xFF690005)
internal val errorContainerDarkForest = Color(0xFF93000A)
internal val onErrorContainerDarkForest = Color(0xFFFFDAD6)
internal val backgroundDarkForest = Color(0xFF11150B)
internal val onBackgroundDarkForest = Color(0xFFE0E4D4)
internal val surfaceDarkForest = Color(0xFF11150B)
internal val onSurfaceDarkForest = Color(0xFFE0E4D4)
internal val surfaceVariantDarkForest = Color(0xFF424937)
internal val onSurfaceVariantDarkForest = Color(0xFFC2CAB2)
internal val outlineDarkForest = Color(0xFF8C947E)
internal val outlineVariantDarkForest = Color(0xFF424937)
internal val scrimDarkForest = Color(0xFF000000)
internal val inverseSurfaceDarkForest = Color(0xFFE0E4D4)
internal val inverseOnSurfaceDarkForest = Color(0xFF2E3227)
internal val inversePrimaryDarkForest = Color(0xFF3F6900)
internal val surfaceDimDarkForest = Color(0xFF11150B)
internal val surfaceBrightDarkForest = Color(0xFF363B2F)
internal val surfaceContainerLowestDarkForest = Color(0xFF0B0F07)
internal val surfaceContainerLowDarkForest = Color(0xFF191D13)
internal val surfaceContainerDarkForest = Color(0xFF1D2117)
internal val surfaceContainerHighDarkForest = Color(0xFF272B21)
internal val surfaceContainerHighestDarkForest = Color(0xFF32362B)

// Ocean Color Palette by HEX: #769CDF
internal val primaryLightOcean = Color(0xFF365E9D)
internal val onPrimaryLightOcean = Color(0xFFFFFFFF)
internal val primaryContainerLightOcean = Color(0xFF769CDF)
internal val onPrimaryContainerLightOcean = Color(0xFF00326A)

internal val secondaryLightOcean = Color(0xFF515F79)
internal val onSecondaryLightOcean = Color(0xFFFFFFFF)
internal val secondaryContainerLightOcean = Color(0xFFD2E0FF)
internal val onSecondaryContainerLightOcean = Color(0xFF55637D)

internal val tertiaryLightOcean = Color(0xFF814A87)
internal val onTertiaryLightOcean = Color(0xFFFFFFFF)
internal val tertiaryContainerLightOcean = Color(0xFFC486C8)
internal val onTertiaryContainerLightOcean = Color(0xFF511D58)

internal val errorLightOcean = Color(0xFFBA1A1A)
internal val onErrorLightOcean = Color(0xFFFFFFFF)
internal val errorContainerLightOcean = Color(0xFFFFDAD6)
internal val onErrorContainerLightOcean = Color(0xFF93000A)

internal val backgroundLightOcean = Color(0xFFF9F9FF)
internal val onBackgroundLightOcean = Color(0xFF1A1C20)

internal val surfaceLightOcean = Color(0xFFF9F9FF)
internal val onSurfaceLightOcean = Color(0xFF1A1C20)
internal val surfaceVariantLightOcean = Color(0xFFDFE2EE)
internal val onSurfaceVariantLightOcean = Color(0xFF434750)
internal val outlineLightOcean = Color(0xFF737781)
internal val outlineVariantLightOcean = Color(0xFFC3C6D2)
internal val scrimLightOcean = Color(0xFF000000)
internal val inverseSurfaceLightOcean = Color(0xFF2F3035)
internal val inverseOnSurfaceLightOcean = Color(0xFFF1F0F6)
internal val inversePrimaryLightOcean = Color(0xFFAAC7FF)

internal val surfaceDimLightOcean = Color(0xFFDAD9DF)
internal val surfaceBrightLightOcean = Color(0xFFF9F9FF)
internal val surfaceContainerLowestLightOcean = Color(0xFFFFFFFF)
internal val surfaceContainerLowLightOcean = Color(0xFFF3F3F9)
internal val surfaceContainerLightOcean = Color(0xFFEEEDF3)
internal val surfaceContainerHighLightOcean = Color(0xFFE8E7ED)
internal val surfaceContainerHighestLightOcean = Color(0xFFE2E2E8)

// Dark Theme Colors
internal val primaryDarkOcean = Color(0xFFAAC7FF)
internal val onPrimaryDarkOcean = Color(0xFF002F64)
internal val primaryContainerDarkOcean = Color(0xFF769CDF)
internal val onPrimaryContainerDarkOcean = Color(0xFF00326A)

internal val secondaryDarkOcean = Color(0xFFB9C7E5)
internal val onSecondaryDarkOcean = Color(0xFF233148)
internal val secondaryContainerDarkOcean = Color(0xFF3C4962)
internal val onSecondaryContainerDarkOcean = Color(0xFFABB9D6)

internal val tertiaryDarkOcean = Color(0xFFF2B0F5)
internal val onTertiaryDarkOcean = Color(0xFF4D1A55)
internal val tertiaryContainerDarkOcean = Color(0xFFC486C8)
internal val onTertiaryContainerDarkOcean = Color(0xFF511D58)

internal val errorDarkOcean = Color(0xFFFFB4AB)
internal val onErrorDarkOcean = Color(0xFF690005)
internal val errorContainerDarkOcean = Color(0xFF93000A)
internal val onErrorContainerDarkOcean = Color(0xFFFFDAD6)

internal val backgroundDarkOcean = Color(0xFF121317)
internal val onBackgroundDarkOcean = Color(0xFFE2E2E8)

internal val surfaceDarkOcean = Color(0xFF121317)
internal val onSurfaceDarkOcean = Color(0xFFE2E2E8)
internal val surfaceVariantDarkOcean = Color(0xFF434750)
internal val onSurfaceVariantDarkOcean = Color(0xFFC3C6D2)
internal val outlineDarkOcean = Color(0xFF8D909B)
internal val outlineVariantDarkOcean = Color(0xFF434750)
internal val scrimDarkOcean = Color(0xFF000000)
internal val inverseSurfaceDarkOcean = Color(0xFFE2E2E8)
internal val inverseOnSurfaceDarkOcean = Color(0xFF2F3035)
internal val inversePrimaryDarkOcean = Color(0xFF365E9D)

internal val surfaceDimDarkOcean = Color(0xFF121317)
internal val surfaceBrightDarkOcean = Color(0xFF38393E)
internal val surfaceContainerLowestDarkOcean = Color(0xFF0C0E12)
internal val surfaceContainerLowDarkOcean = Color(0xFF1A1C20)
internal val surfaceContainerDarkOcean = Color(0xFF1E2024)
internal val surfaceContainerHighDarkOcean = Color(0xFF282A2E)
internal val surfaceContainerHighestDarkOcean = Color(0xFF333539)