ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.example.HttpKt.configureHttp
      - com.example.SerializationKt.configureSerialization
      - com.example.SecurityKt.configureSecurity
      - com.example.KoinKt.configureKoin
      - com.example.ExposedKt.configureExposed
      - com.example.PostgresKt.configurePostgres
      - com.example.RoutingKt.configureRouting
