package com.example.gamification.model

import com.example.designsystem.picture.BloomAchievementImages

object AchievementRegistry {
    val allAchievements: List<Achievement> =
        listOf(
            Achievement(
                0,
                BloomAchievementImages.PLACEHOLDER.name,
                "Первая посадка",
                "Создать первую привычку",
                HabitCreatedCondition(1),
                50,
            ),
            Achievement(
                1,
                BloomAchievementImages.PLACEHOLDER.name,
                "Первая посадка",
                "Создать первую привычку",
                HabitCreatedCondition(10),
                50,
            ),
            Achievement(
                2,
                BloomAchievementImages.PLACEHOLDER.name,
                "Недельный садовод",
                "Поддерживать привычку 7 дней подряд",
                StreakCondition(7),
                100,
            ),
            Achievement(
                3,
                BloomAchievementImages.PLACEHOLDER.name,
                "Пять ростков",
                "Создать 5 привычек",
                HabitCreatedCondition(5),
                75,
            ),
            Achievement(
                4,
                BloomAchievementImages.PLACEHOLDER.name,
                "Густые заросли",
                "Создать 25 привычек",
                HabitCreatedCondition(25),
                150,
            ),
            Achievement(
                5,
                BloomAchievementImages.PLACEHOLDER.name,
                "Целая роща",
                "Создать 50 привычек",
                HabitCreatedCondition(50),
                200,
            ),
            Achievement(
                6,
                BloomAchievementImages.PLACEHOLDER.name,
                "Архивариус сада",
                "Создать 100 привычек",
                HabitCreatedCondition(100),
                300,
            ),
            Achievement(
                7,
                BloomAchievementImages.PLACEHOLDER.name,
                "Двухнедельный побег",
                "Серия 14 дней подряд",
                StreakCondition(14),
                150,
            ),
            Achievement(
                8,
                BloomAchievementImages.PLACEHOLDER.name,
                "Месячный ствол",
                "Серия 30 дней подряд",
                StreakCondition(30),
                250,
            ),
            Achievement(
                9,
                BloomAchievementImages.PLACEHOLDER.name,
                "Сезонный садовник",
                "Серия 90 дней подряд",
                StreakCondition(90),
                500,
            ),
            Achievement(
                10,
                BloomAchievementImages.PLACEHOLDER.name,
                "Годовой дуб",
                "Серия 365 дней подряд",
                StreakCondition(365),
                1000,
            ),
            Achievement(
                11,
                BloomAchievementImages.PLACEHOLDER.name,
                "Первый урожай",
                "Завершить 5 привычек",
                HabitCompletedCondition(5),
                75,
            ),
            Achievement(
                12,
                BloomAchievementImages.PLACEHOLDER.name,
                "Щедрый сад",
                "Завершить 50 привычек",
                HabitCompletedCondition(50),
                200,
            ),
            Achievement(
                13,
                BloomAchievementImages.PLACEHOLDER.name,
                "Обильный сбор",
                "Завершить 200 привычек",
                HabitCompletedCondition(200),
                400,
            ),
            Achievement(
                14,
                BloomAchievementImages.PLACEHOLDER.name,
                "Золотой плод",
                "Завершить 500 привычек",
                HabitCompletedCondition(500),
                800,
            ),
            Achievement(
                15,
                BloomAchievementImages.PLACEHOLDER.name,
                "Создатель задач",
                "Создать 10 задач",
                TaskCreatedCondition(10),
                50,
            ),
            Achievement(
                16,
                BloomAchievementImages.PLACEHOLDER.name,
                "Архитектор дня",
                "Создать 50 задач",
                TaskCreatedCondition(50),
                100,
            ),
            Achievement(
                17,
                BloomAchievementImages.PLACEHOLDER.name,
                "Планировщик",
                "Создать 100 задач",
                TaskCreatedCondition(100),
                150,
            ),
            Achievement(
                18,
                BloomAchievementImages.PLACEHOLDER.name,
                "Генератор дел",
                "Создать 500 задач",
                TaskCreatedCondition(500),
                300,
            ),
            Achievement(
                19,
                BloomAchievementImages.PLACEHOLDER.name,
                "Исполнитель",
                "Завершить 10 задач",
                TaskCompletedCondition(10),
                50,
            ),
            Achievement(
                20,
                BloomAchievementImages.PLACEHOLDER.name,
                "Трудяга",
                "Завершить 100 задач",
                TaskCompletedCondition(100),
                200,
            ),
            Achievement(
                21,
                BloomAchievementImages.PLACEHOLDER.name,
                "Мастер продуктивности",
                "Завершить 500 задач",
                TaskCompletedCondition(500),
                500,
            ),
            Achievement(
                22,
                BloomAchievementImages.PLACEHOLDER.name,
                "Легенда эффективности",
                "Завершить 1000 задач",
                TaskCompletedCondition(1000),
                800,
            ),
            Achievement(
                23,
                BloomAchievementImages.PLACEHOLDER.name,
                "Новичок-садовник",
                "Достичь 5 уровня",
                LevelCondition(5),
                100,
            ),
            Achievement(
                24,
                BloomAchievementImages.PLACEHOLDER.name,
                "Опытный ботаник",
                "Достичь 10 уровня",
                LevelCondition(10),
                200,
            ),
            Achievement(
                25,
                BloomAchievementImages.PLACEHOLDER.name,
                "Эксперт флористики",
                "Достичь 25 уровня",
                LevelCondition(25),
                500,
            ),
            Achievement(
                26,
                BloomAchievementImages.PLACEHOLDER.name,
                "Легенда оазиса",
                "Достичь 50 уровня",
                LevelCondition(50),
                1000,
            ),
            Achievement(
                27,
                BloomAchievementImages.PLACEHOLDER.name,
                "Копилка семян",
                "Накопить 1000 монет",
                CoinsCondition(1000),
                100,
            ),
            Achievement(
                28,
                BloomAchievementImages.PLACEHOLDER.name,
                "Банкир сада",
                "Накопить 5000 монет",
                CoinsCondition(5000),
                300,
            ),
            Achievement(
                29,
                BloomAchievementImages.PLACEHOLDER.name,
                "Сокровищница",
                "Накопить 10000 монет",
                CoinsCondition(10000),
                500,
            ),
        )
}
